name: age_of_gold
description: Age Of Gold

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flame: ^1.4.0
  universal_html: ^2.0.8
  intl: ^0.17.0
  flutter_lints: ^2.0.1
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  flutter_simple_dependency_injection: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/tile_variants/variant_1.png
    - assets/images/tile_variants/variant_2.png
    - assets/images/tile_variants/variant_3.png
    - assets/images/tile_variants/variant_4.png
    - assets/images/tile_variants/variant_5.png
    - assets/images/tile_variants/variant_6.png
    - assets/images/tile_variants/variant_7.png
    - assets/images/tile_variants/variant_8.png
    - assets/images/tile_variants/variant_9.png
    - assets/images/tile_variants/variant_10.png
    - assets/images/tile_variants/variant_11.png
    - assets/images/tile_variants/variant_12.png
    - assets/images/tiles/00a368_noise1.png
    - assets/images/tiles/00cc78_noise1.png
    - assets/images/tiles/000000_noise1.png
    - assets/images/tiles/6a5cff_noise1.png
    - assets/images/tiles/6d482f_noise1.png
    - assets/images/tiles/7eed56_noise1.png
    - assets/images/tiles/9c6926_noise1.png
    - assets/images/tiles/009eaa_noise1.png
    - assets/images/tiles/51e9f4_noise1.png
    - assets/images/tiles/493ac1_noise1.png
    - assets/images/tiles/00756f_noise1.png
    - assets/images/tiles/811e9f_noise1.png
    - assets/images/tiles/898d90_noise1.png
    - assets/images/tiles/2450a4_noise1.png
    - assets/images/tiles/3690ea_noise1.png
    - assets/images/tiles/b44ac0_noise1.png
    - assets/images/tiles/be0039_noise1.png
    - assets/images/tiles/d4d7d9_noise1.png
    - assets/images/tiles/ff99aa_noise1.png
    - assets/images/tiles/ff3881_noise1.png
    - assets/images/tiles/ff4500_noise1.png
    - assets/images/tiles/ffa800_noise1.png
    - assets/images/tiles/ffd635_noise1.png
    - assets/images/tiles/ffffff_noise1.png
    - assets/images/brocast_transparent.png
    - assets/images/Github_logo_PNG1.png

